DROP VIEW IF EXISTS pop.v_population_preflop;

CREATE VIEW
    pop.v_population_preflop AS
SELECT
    r.id_limit,
    r.limit_name,
    r.amt_sb,
    r.amt_bb,
    r.player_count,
    r.total_hands,
    r.rfi_lj,
    r.rfi_hj,
    r.rfi_co,
    r.rfi_btn,
    r.rfi_sb,
    c.call_hj_vs_lj,
    c.call_co_vs_lj,
    c.call_co_vs_hj,
    c.call_btn_vs_lj,
    c.call_btn_vs_hj,
    c.call_btn_vs_co,
    c.call_sb_vs_lj,
    c.call_sb_vs_hj,
    c.call_sb_vs_co,
    c.call_sb_vs_btn,
    c.call_bb_vs_lj,
    c.call_bb_vs_hj,
    c.call_bb_vs_co,
    c.call_bb_vs_btn,
    c.call_bb_vs_sb,
    t.threebet_hj_vs_lj,
    t.threebet_co_vs_lj,
    t.threebet_co_vs_hj,
    t.threebet_btn_vs_lj,
    t.threebet_btn_vs_hj,
    t.threebet_btn_vs_co,
    t.threebet_sb_vs_lj,
    t.threebet_sb_vs_hj,
    t.threebet_sb_vs_co,
    t.threebet_sb_vs_btn,
    t.threebet_bb_vs_lj,
    t.threebet_bb_vs_hj,
    t.threebet_bb_vs_co,
    t.threebet_bb_vs_btn,
    t.threebet_bb_vs_sb,
    f.fold_hj_vs_lj,
    f.fold_co_vs_lj,
    f.fold_co_vs_hj,
    f.fold_btn_vs_lj,
    f.fold_btn_vs_hj,
    f.fold_btn_vs_co,
    f.fold_sb_vs_lj,
    f.fold_sb_vs_hj,
    f.fold_sb_vs_co,
    f.fold_sb_vs_btn,
    f.fold_bb_vs_lj,
    f.fold_bb_vs_hj,
    f.fold_bb_vs_co,
    f.fold_bb_vs_btn,
    f.fold_bb_vs_sb,
    fb.fourbet_lj_vs_hj,
    fb.fourbet_lj_vs_co,
    fb.fourbet_lj_vs_btn,
    fb.fourbet_lj_vs_sb,
    fb.fourbet_lj_vs_bb,
    fb.fourbet_hj_vs_co,
    fb.fourbet_hj_vs_btn,
    fb.fourbet_hj_vs_sb,
    fb.fourbet_hj_vs_bb,
    fb.fourbet_co_vs_btn,
    fb.fourbet_co_vs_sb,
    fb.fourbet_co_vs_bb,
    fb.fourbet_btn_vs_sb,
    fb.fourbet_btn_vs_bb,
    fb.fourbet_sb_vs_bb,
    cvt.call_lj_vs_3bet_hj,
    cvt.call_lj_vs_3bet_co,
    cvt.call_lj_vs_3bet_btn,
    cvt.call_lj_vs_3bet_sb,
    cvt.call_lj_vs_3bet_bb,
    cvt.call_hj_vs_3bet_co,
    cvt.call_hj_vs_3bet_btn,
    cvt.call_hj_vs_3bet_sb,
    cvt.call_hj_vs_3bet_bb,
    cvt.call_co_vs_3bet_btn,
    cvt.call_co_vs_3bet_sb,
    cvt.call_co_vs_3bet_bb,
    cvt.call_btn_vs_3bet_sb,
    cvt.call_btn_vs_3bet_bb,
    cvt.call_sb_vs_3bet_bb,
    fvt.fold_lj_vs_3bet_hj,
    fvt.fold_lj_vs_3bet_co,
    fvt.fold_lj_vs_3bet_btn,
    fvt.fold_lj_vs_3bet_sb,
    fvt.fold_lj_vs_3bet_bb,
    fvt.fold_hj_vs_3bet_co,
    fvt.fold_hj_vs_3bet_btn,
    fvt.fold_hj_vs_3bet_sb,
    fvt.fold_hj_vs_3bet_bb,
    fvt.fold_co_vs_3bet_btn,
    fvt.fold_co_vs_3bet_sb,
    fvt.fold_co_vs_3bet_bb,
    fvt.fold_btn_vs_3bet_sb,
    fvt.fold_btn_vs_3bet_bb,
    fvt.fold_sb_vs_3bet_bb
FROM
    pop.v_population_rfi r
    LEFT JOIN pop.v_population_call_vs_open c ON c.id_limit = r.id_limit
    LEFT JOIN pop.v_population_3bet_vs_open t ON t.id_limit = r.id_limit
    LEFT JOIN pop.v_population_fold_vs_open f ON f.id_limit = r.id_limit
    LEFT JOIN pop.v_population_4bet_vs_3bet fb on fb.id_limit = r.id_limit
    LEFT JOIN pop.v_population_call_vs_3bet cvt on cvt.id_limit = r.id_limit
    LEFT JOIN pop.v_population_fold_vs_3bet fvt on fvt.id_limit = r.id_limit;